<?php

global $shortcuts;

$shortcuts['softether5'] = array();
$shortcuts['softether5']['main'] = "/vpn_softether5.php";

$shortcuts['vpnserver'] = array();
$shortcuts['vpnserver']['main'] = "/vpn_softether5.php";
$shortcuts['vpnserver']['service'] = "vpnserver";

$shortcuts['vpnbridge'] = array();
$shortcuts['vpnbridge']['main'] = "/vpn_softether5.php";
$shortcuts['vpnbridge']['service'] = "vpnbridge";

?>
